### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by bpsizemore** [Gnovel/Srcalyzer#15]
We need to lock in an official database design and have it approved by Reaser. This will allows us to move forward with the creation of the database.

**Comment by tmduckworth** [comment]
[Srcalyzer DB Design.pdf](https://github.com/Gnovel/Srcalyzer/files/328962/Srcalyzer.DB.Design.pdf)

Here it is Please leave comments and suggestions!

**Comment by Bloodcinder** [comment]
Looks much better. Some issues:

1) You can normalize StudentEnrollment and EducatorEnrollment into a single Enrollment table with a flag that indicates whether the enrollment is for the educator or not, since there's no practical reason to need two different tables for matching user and course ID's. This would still allow multiple educators to be associated with a course. However, since you already have an owner ID in the Course, I don't know why you would need educator enrollments in general, unless you're using it for TA's. Please clarify.

2) Some relationships (and the fields that constitute them) can be normalized. Notice that an Assignment knows which course ID it belongs to. So there's no reason that a Report or a Submission (which already matches to a particular Assignment) needs to also store the course ID. Avoid duplicating data across multiple tables. This will cut down on the number of relationships you have and make the model easier to understand in addition to being more efficient and mutation-safe.

3) It looks like Report is both one-to-many and many-to-one with Submission... which de facto means they are many-to-many and need to be normalized in some way. Do those even need to be separate tables? When would one Report match to many Submissions? When would one Submission match to many reports? I need clarification to understand. It seems to me like any single submission would have a single grading report associated with it and that the relationship would be one-to-one, in which case the two tables could be merged into a single submission table.

4) Be consistent with pluralization. You have Assignments and Courses (plural) but also Enrollment and Report (singular). There are justifications for either style, but pick one and be consistent.

Good work. Keep it up.

**Comment by tmduckworth** [comment]
I think we successfully implemented your suggestions. Let us know if you have any other suggestions. 
[SrcalyzerDB2.pdf](https://github.com/Gnovel/Srcalyzer/files/348814/SrcalyzerDB2.pdf)

**Comment by Bloodcinder** [comment]
This looks fine. Anything that needs to be revised should evolve naturally during the work based on what you've shown.
